augmentation_config:
  use_augmentation: false
callbacks:
- class_path: src.utils.callbacks.EarlyStopping
  init_args:
    patience: 7
    verbose: true
- class_path: src.utils.callbacks.ModelCheckpoint
  init_args:
    filepath: best_convnext.pth
    monitor: val_loss
    save_best_only: true
global_config:
  batch_size: 32
  data_dir: data/gold/datasets/v10/train_val
  dataset_name: v10
  device: auto
  experiment_name: convnext_v10_BR_opt_aug
  max_epochs: 30
  mlflow_uri: file:///mlruns
  num_workers: 0
loss:
  params:
    label_smoothing: 0.11922140490616356
  type: CrossEntropyLoss
model_type: convnext
optimizer:
  params:
    lr: 0.00023525631599871242
    weight_decay: 0.04819640028407592
  type: AdamW
params:
  architecture: convnext_tiny
  dropout: 0.23015540856031444
  hidden_units: 512
  pretrained: true
  unfreeze_layers: 5
  weights: IMAGENET1K_V1
scheduler:
  params:
    factor: 0.15316611732354923
    min_lr: 1.0e-06
    mode: min
    patience: 3
  type: ReduceLROnPlateau
