augmentation_config:
  use_augmentation: false
callbacks:
- class_path: src.utils.callbacks.EarlyStopping
  init_args:
    patience: 15
    verbose: true
- class_path: src.utils.callbacks.ModelCheckpoint
  init_args:
    filepath: best_swin.pth
    monitor: val_loss
    save_best_only: true
global_config:
  batch_size: 16
  data_dir: data/gold/datasets/v1/train_val
  dataset_name: v1
  device: auto
  experiment_name: swin_v1_AB_opt_aug
  max_epochs: 30
  mlflow_uri: file:///mlruns
  num_workers: 0
loss:
  params:
    label_smoothing: 0.015741495502651387
  type: CrossEntropyLoss
model_type: swin
optimizer:
  params:
    lr: 9.632129365438643e-05
    weight_decay: 0.010174491974992865
  type: AdamW
params:
  architecture: swin_t
  dropout: 0.015873506280841665
  hidden_units: 512
  pretrained: true
  unfreeze_layers: 4
  weights: IMAGENET1K_V1
scheduler:
  params:
    T_0: 9
    T_mult: 2
    eta_min: 1.0e-06
  type: CosineAnnealingWarmRestarts
