augmentation_config:
  per_image_aug_method: none
  use_augmentation: true
callbacks:
- class_path: src.utils.callbacks.EarlyStopping
  init_args:
    patience: 7
    verbose: true
- class_path: src.utils.callbacks.ModelCheckpoint
  init_args:
    filepath: best_model_inception.pth
    monitor: val_loss
    save_best_only: true
global_config:
  batch_size: 64
  data_dir: data/gold/datasets/v10/train_val
  dataset_name: v10
  device: auto
  experiment_name: inception_v10_BR_opt_aug
  max_epochs: 30
  mlflow_uri: file:///mlruns
  num_workers: 0
loss:
  params:
    label_smoothing: 0.1
  type: CrossEntropyLoss
model_type: inception
optimizer:
  params:
    lr: 0.0005717560279735875
    weight_decay: 0.00013390553270537905
  type: AdamW
params:
  architecture: inception_v3
  dropout: 0.44224529364828186
  hidden_units: 1024
  pretrained: true
  unfreeze_layers: 6
  weights: IMAGENET1K_V1
scheduler:
  params:
    factor: 0.19880287141142566
    min_lr: 1.0e-06
    mode: min
    patience: 5
  type: ReduceLROnPlateau
