augmentations: {}
callbacks:
- class_path: src.utils.callbacks.EarlyStopping
  init_args:
    patience: 7
    verbose: true
- class_path: src.utils.callbacks.ModelCheckpoint
  init_args:
    filepath: best_vit.pth
    monitor: val_loss
    save_best_only: true
global_config:
  batch_size: 32
  data_dir: data/gold/datasets/v1/train_val
  dataset_name: v1
  device: auto
  experiment_name: vit_v1_AB_opt
  max_epochs: 30
  mlflow_uri: file:///mlruns
  num_workers: 0
loss:
  params:
    label_smoothing: 0.030397604911472142
  type: CrossEntropyLoss
model_type: vit
optimizer:
  params:
    lr: 1.6481430203639538e-05
    weight_decay: 0.09835559245321211
  type: AdamW
params:
  architecture: vit_b_32
  dropout: 0.023553920686653136
  hidden_units: 256
  pretrained: true
  unfreeze_layers: 3
  weights: IMAGENET1K_V1
scheduler:
  params:
    T_0: 12
    T_mult: 2
    eta_min: 1.0e-06
  type: CosineAnnealingWarmRestarts
train_transform:
  transforms:
  - name: Resize
    params:
      size:
      - 224
      - 224
val_transform:
  transforms:
  - name: Resize
    params:
      size:
      - 224
      - 224
