augmentation_config:
  use_augmentation: false
global_config:
  batch_size: 32
  dataset_name: v12
  device: auto
  experiment_name: ELITE_EVAL_v12_vit
  max_epochs: 30
  mlflow_uri: file:///Users/rodrigoqaz/Documents/projetos/mecai.dissertacao/mlruns
  num_workers: 4
  seed: 42
model_type: vit
params:
  architecture: vit_b_16
  augmentations: '{}'
  callbacks: '[{''class_path'': ''src.utils.callbacks.EarlyStopping'', ''init_args'':
    {''patience'': 7, ''verbose'': True}}, {''class_path'': ''src.utils.callbacks.ModelCheckpoint'',
    ''init_args'': {''filepath'': ''best_vit.pth'', ''monitor'': ''val_loss'', ''save_best_only'':
    True}}]'
  data_dir: data/gold/datasets/v12/train_val
  device: auto
  dropout: '0.006708761095055561'
  experiment_name: ViT
  global_config: '{''data_dir'': ''data/gold/datasets/v12/train_val'', ''experiment_name'':
    ''ViT'', ''mlflow_uri'': ''file:///mlruns'', ''dataset_name'': ''v12'', ''max_epochs'':
    30, ''batch_size'': 32, ''num_workers'': 0, ''device'': ''auto'', ''seed'': 42}'
  hidden_units: '256'
  input_channels: '15'
  loss: '{''type'': ''CrossEntropyLoss'', ''params'': {''label_smoothing'': 0.04663454892987416}}'
  mlflow_uri: file:///mlruns
  num_classes: '10'
  num_workers: '0'
  optimizer: '{''type'': ''AdamW'', ''params'': {''lr'': 1.3328781863630876e-05, ''weight_decay'':
    0.017966794723070632}}'
  params: '{''architecture'': ''vit_b_16'', ''pretrained'': True, ''unfreeze_layers'':
    2, ''hidden_units'': 256, ''dropout'': 0.006708761095055561, ''weights'': ''IMAGENET1K_V1''}'
  pretrained: 'True'
  scheduler: '{''type'': ''ReduceLROnPlateau'', ''params'': {''mode'': ''min'', ''patience'':
    8, ''factor'': 0.3436438119117687, ''min_lr'': 1e-07}}'
  unfreeze_layers: '2'
  weights: IMAGENET1K_V1
