augmentation_config:
  use_augmentation: false
global_config:
  batch_size: 32
  dataset_name: v9
  device: auto
  experiment_name: ELITE_EVAL_v9_densenet
  max_epochs: 30
  mlflow_uri: file:///Users/rodrigoqaz/Documents/projetos/mecai.dissertacao/mlruns
  num_workers: 4
  seed: 42
model_type: densenet
params:
  architecture: densenet121
  augmentations: '{}'
  callbacks: '[{''class_path'': ''src.utils.callbacks.EarlyStopping'', ''init_args'':
    {''patience'': 7, ''verbose'': True}}, {''class_path'': ''src.utils.callbacks.ModelCheckpoint'',
    ''init_args'': {''filepath'': ''best_densenet.pth'', ''monitor'': ''val_loss'',
    ''save_best_only'': True}}]'
  data_dir: data/gold/datasets/v9/train_val
  device: auto
  dropout: '0.2762953594860663'
  experiment_name: DenseNet
  global_config: '{''data_dir'': ''data/gold/datasets/v9/train_val'', ''experiment_name'':
    ''DenseNet'', ''mlflow_uri'': ''file:///mlruns'', ''dataset_name'': ''v9'', ''seed'':
    42, ''max_epochs'': 30, ''batch_size'': 32, ''num_workers'': 0, ''device'': ''auto''}'
  hidden_units: '256'
  input_channels: '3'
  loss: '{''type'': ''CrossEntropyLoss'', ''params'': {''label_smoothing'': 0.1}}'
  mlflow_uri: file:///mlruns
  num_classes: '10'
  num_workers: '0'
  optimizer: '{''type'': ''AdamW'', ''params'': {''lr'': 0.0002945164812704837, ''weight_decay'':
    0.00017904319826816606}}'
  params: '{''architecture'': ''densenet121'', ''pretrained'': True, ''unfreeze_layers'':
    6, ''hidden_units'': 256, ''dropout'': 0.2762953594860663, ''weights'': ''IMAGENET1K_V1''}'
  pretrained: 'True'
  scheduler: '{''type'': ''ReduceLROnPlateau'', ''params'': {''mode'': ''min'', ''patience'':
    3, ''factor'': 0.2672553321058638, ''min_lr'': 1e-07}}'
  unfreeze_layers: '6'
  weights: IMAGENET1K_V1
