augmentation_config:
  batch_level_aug_method: cutmix
  mix_alpha: 0.26132509758540307
  per_image_aug_method: none
  use_augmentation: true
callbacks:
- class_path: src.utils.callbacks.EarlyStopping
  init_args:
    patience: 7
    verbose: true
- class_path: src.utils.callbacks.ModelCheckpoint
  init_args:
    filepath: best_model_restnet.pth
    monitor: val_loss
    save_best_only: true
global_config:
  batch_size: 64
  data_dir: data/gold/datasets/v8/train_val
  dataset_name: v8
  device: auto
  experiment_name: resnet_v8_AB_opt_aug
  max_epochs: 30
  mlflow_uri: file:///mlruns
  num_workers: 0
loss:
  params:
    label_smoothing: 0.1
  type: CrossEntropyLoss
model_type: resnet
optimizer:
  params:
    lr: 0.002323089841417065
    weight_decay: 4.1819500324607076e-05
  type: SGD
params:
  architecture: resnet34
  dropout: 0.4353330428792929
  hidden_units: 512
  pretrained: true
  unfreeze_layers: 2
  weights: IMAGENET1K_V1
scheduler:
  params:
    factor: 0.10527168575236939
    min_lr: 1.0e-06
    mode: min
    patience: 3
  type: ReduceLROnPlateau
