augmentation_config:
  use_augmentation: false
callbacks:
- class_path: src.utils.callbacks.EarlyStopping
  init_args:
    patience: 7
    verbose: true
- class_path: src.utils.callbacks.ModelCheckpoint
  init_args:
    filepath: best_model_inception.pth
    monitor: val_loss
    save_best_only: true
global_config:
  batch_size: 32
  data_dir: data/gold/datasets/v12/train_val
  dataset_name: v12
  device: auto
  experiment_name: inception_v12_BR_opt_aug
  max_epochs: 30
  mlflow_uri: file:///mlruns
  num_workers: 0
loss:
  params:
    label_smoothing: 0.1
  type: CrossEntropyLoss
model_type: inception
optimizer:
  params:
    lr: 0.00029656683009624115
    weight_decay: 1.6651249411303476e-05
  type: AdamW
params:
  architecture: inception_v3
  dropout: 0.5904897567844563
  hidden_units: 1024
  pretrained: true
  unfreeze_layers: 6
  weights: IMAGENET1K_V1
scheduler:
  params:
    factor: 0.10998034879084179
    min_lr: 1.0e-06
    mode: min
    patience: 5
  type: ReduceLROnPlateau
