augmentation_config:
  use_augmentation: false
callbacks:
- class_path: src.utils.callbacks.EarlyStopping
  init_args:
    patience: 7
    verbose: true
- class_path: src.utils.callbacks.ModelCheckpoint
  init_args:
    filepath: best_densenet.pth
    monitor: val_loss
    save_best_only: true
global_config:
  batch_size: 16
  data_dir: data/gold/datasets/v8/train_val
  dataset_name: v8
  device: auto
  experiment_name: densenet_v8_AB_opt_aug
  max_epochs: 30
  mlflow_uri: file:///mlruns
  num_workers: 0
loss:
  params:
    label_smoothing: 0.1
  type: CrossEntropyLoss
model_type: densenet
optimizer:
  params:
    lr: 0.00010994335574766199
    weight_decay: 0.0008706020878304854
  type: AdamW
params:
  architecture: densenet121
  dropout: 0.41242177333881364
  hidden_units: 256
  pretrained: true
  unfreeze_layers: 2
  weights: IMAGENET1K_V1
scheduler:
  params:
    factor: 0.18493564427131048
    min_lr: 1.0e-06
    mode: min
    patience: 7
  type: ReduceLROnPlateau
