augmentation_config:
  batch_level_aug_method: none
  per_image_aug_method: none
  use_augmentation: true
callbacks:
- class_path: src.utils.callbacks.EarlyStopping
  init_args:
    patience: 7
    verbose: true
- class_path: src.utils.callbacks.ModelCheckpoint
  init_args:
    filepath: best_model_vggnet.pth
    monitor: val_loss
    save_best_only: true
global_config:
  batch_size: 32
  data_dir: data/gold/datasets/v12/train_val
  dataset_name: v12
  device: auto
  experiment_name: vgg_v12_BR_opt_aug
  max_epochs: 30
  mlflow_uri: file:///mlruns
  num_workers: 0
loss:
  params:
    label_smoothing: 0.1
  type: CrossEntropyLoss
model_type: vgg
optimizer:
  params:
    lr: 0.0066847068130844785
    weight_decay: 0.000846998603200694
  type: SGD
params:
  architecture: vgg19_bn
  dropout: 0.6373692981285851
  hidden_units: 256
  pretrained: true
  unfreeze_layers: 5
  weights: IMAGENET1K_V1
scheduler:
  params:
    factor: 0.1
    mode: min
    patience: 3
  type: ReduceLROnPlateau
