augmentation_config:
  use_augmentation: false
callbacks:
- class_path: src.utils.callbacks.EarlyStopping
  init_args:
    patience: 7
    verbose: true
- class_path: src.utils.callbacks.ModelCheckpoint
  init_args:
    filepath: best_densenet.pth
    monitor: val_loss
    save_best_only: true
global_config:
  batch_size: 16
  data_dir: data/gold/datasets/v9/train_val
  dataset_name: v9
  device: auto
  experiment_name: densenet_v10_AM_opt_aug
  max_epochs: 30
  mlflow_uri: file:///mlruns
  num_workers: 0
loss:
  params:
    label_smoothing: 0.1
  type: CrossEntropyLoss
model_type: densenet
optimizer:
  params:
    lr: 0.00032885423038428533
    weight_decay: 3.808631426311798e-05
  type: AdamW
params:
  architecture: densenet121
  dropout: 0.28394773802408146
  hidden_units: 256
  pretrained: true
  unfreeze_layers: 6
  weights: IMAGENET1K_V1
scheduler:
  params:
    factor: 0.27254412189101596
    min_lr: 1.0e-06
    mode: min
    patience: 3
  type: ReduceLROnPlateau
